# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4df256952564bab6254c2c8aea8c53bc5a60aba80dd9d0897ea919342b8bb0b80c3aff58692319925bd7ffd27265fbd265c93a2dcd04eda4850e9590f67fbd8

test:
  secret_key_base: b601240ccf55e470cca31bdcb78d64ac1ca55d477d46f79fb8d88a405aefed731a1ba0d5a673ffa980519288f9d542b761e6f537137996c89d0ffda72c4d5009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
